services:
  backend:
    environment:
      - FRONTEND_URL=http://localhost:3000
    ports:
      - "3001:3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend:/app

  frontend:
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3001
