version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    stdin_open: true
    tty: true

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3001
